### Variables
@baseUrl = http://localhost:3000/api

### 1. Compress Image (Returns Base64 + Metadata)
# This will return a JSON object containing the base64 string of the compressed image
POST {{baseUrl}}/image/compress
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="quality"

50
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="test.jepg"
Content-Type: image/jpeg

< ./test/fixtures/sample.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### 2. Compress and Download (Returns Binary Image)
# This will return the actual .webp file
POST {{baseUrl}}/image/compress/download
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="quality"

80
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="test.jpg"
Content-Type: image/jpeg

< ./test/fixtures/sample.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
